name: Update README with Recent Activity

on:
  schedule:
    - cron: "*/30 * * * *"   # corre cada 30 minutos
  workflow_dispatch:          # permite lanzarlo manualmente desde Actions

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update recent activity in README
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Si quisieras usar otro nombre/ruta de config, agrega:
        # with:
        #   CONFIG_FILE: ./.github/recent-activity.config.yml

        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
