name: Update README

on:
  schedule:
    - cron: "0 */12 * * *" # cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_readme:
    name: Update Profile README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update recent activity section
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config_file_path: .github/recent-activity.config.yml
          commit_branch: main     # cámbialo a master si tu rama por defecto es master